---
title: "data_preprocess"
author: "Xiaoting Chen"
date: "2023-12-13"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## packages


```{r}
library(tidyr)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(haven)
```

## data

### Basic dataset from ENAR official
```{r}
load("~/Documents/research/ENAR/data/nhanes_data.rda")

# data dictionary
load("~/Documents/research/ENAR/data/nhanes_key.rda")
load("~/Documents/research/ENAR/data/key_guide.rda")
```


### Extra covariates

read in data files
```{r}
filenames <- list.files(path = "~/Documents/research/ENAR/data",
                        pattern = "*.XPT",
                        full.names = TRUE)
ldf <- lapply(filenames, read_xpt)
```

rename data files
```{r}
# ALQ
for (i in 1:10) {
  assign(paste("ALQ",i, sep = "_"), ldf[[i]])
}

# DEMO
for (i in 11:20) {
  assign(paste("DEMO",(i-10), sep = "_"), ldf[[i]])
}

# SMQ
for (i in 21:30) {
  assign(paste("SMQ",i-20, sep = "_"), ldf[[i]])
}
```

select variables of interest

```{r alq_select}
ALQ_1 = ALQ_1[ , c("SEQN", "ALQ100")]
ALQ_2 = ALQ_2[ , c("SEQN", "ALD100")]
ALQ_3 = ALQ_3[ , c("SEQN", "ALQ101")]
ALQ_4 = ALQ_4[ , c("SEQN", "ALQ101")]
ALQ_5 = ALQ_5[ , c("SEQN", "ALQ101")]
ALQ_6 = ALQ_6[ , c("SEQN", "ALQ101")]
ALQ_7 = ALQ_7[ , c("SEQN", "ALQ101")]
ALQ_8 = ALQ_8[ , c("SEQN", "ALQ101")]
ALQ_9 = ALQ_9[ , c("SEQN", "ALQ101")]
ALQ_10 = ALQ_10[ , c("SEQN", "ALQ101")]
```