---
title: "Exploratory data analysis"
author: "Xiaoting Chen"
date: "2023-12-01"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Prep


```{r}
#library(cardioStatsUSA)
library(tidyr)
library(tidyverse)
library(dplyr)
library(ggplot2)
```

```{r}
# raw data
load("~/Documents/research/ENAR/nhanes_data.rda")

# data dictionary
load("~/Documents/research/ENAR/nhanes_key.rda")
load("~/Documents/research/ENAR/key_guide.rda")
```


## Outcome distribution

```{r}
proportions <- nhanes_data %>%
  group_by(svy_year, bp_control_140_90) %>%
  summarise(count = n()) %>%
  mutate(percentage = count / sum(count) * 100)

# Create a stacked bar plot
ggplot(proportions, aes(x = svy_year, y = percentage, fill = bp_control_140_90)) +
  geom_bar(stat = "identity", position = "stack") +
  labs(title = "BP Control (140/90) Percentage",
       x = "Survey Year",
       y = "Percentage") +
  scale_fill_manual(values = c("Yes" = "blue", "No" = "red")) +
  geom_text(aes(label = sprintf("%.1f%%", percentage)), position = position_stack(vjust = 0.5)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```

## BP SYS vs covariates

Ranked cholesterol 
```{r}
nhanes_data$chol_total_rank <- dense_rank(nhanes_data$chol_total)
ggplot(data = nhanes_data) + geom_point(aes(x = chol_total_rank, y = bp_sys_mean, color = bp_control_140_90))
```

## EDA for POTS
Code from some preliminary analysis in EVA.R
```{r}
load("data/nhanes_data.rda")

#split by survey year (train on 4 waves, predict prevalence on next 4 waves)
data_train1 <- nhanes_data %>%
  filter(svy_year %in% c("1999-2000", "2001-2002", "2003-2004", "2005-2006"))

# filter by observations without missing blood pressure data (sys_mean)
data_train1_clean <- data_train1 %>%
  select(svy_id, svy_year, bp_sys_mean) %>%
  filter(!is.na(bp_sys_mean)) #21205 - 20095 = 1110 observations removed

# create dataset for yearly means and sd
## mean blood pressure
bp_yearly_data <- nhanes_data %>%
  group_by(svy_year, demo_race) %>%
  transmute(survey_year = svy_year,
            race = demo_race,
            BP_sys = mean(bp_sys_mean, na.rm = TRUE),
            BP_sys_sd = sd(bp_sys_mean, na.rm = TRUE),
            BP_dia = mean(bp_dia_mean, na.rm = TRUE),
            BP_dia_sd = sd(bp_dia_mean, na.rm = TRUE),
            n = n()) %>%
  unique() %>%
  mutate(lower.sys = BP_sys - 1.96*BP_sys_sd/sqrt(n),
         upper.sys = BP_sys + 1.96*BP_sys_sd/sqrt(n),
         lower.dia = BP_dia - 1.96*BP_dia_sd/sqrt(n),
         upper.dia = BP_dia + 1.96*BP_dia_sd/sqrt(n))

# yearly mean BP and 95% CI
ggplot(data = bp_yearly_data) +
  geom_point(aes(x = survey_year, y = BP_sys, color = race)) +
  geom_line(aes(x = survey_year, y = BP_sys, color = race, group = race)) +
  geom_linerange(aes(x = survey_year, y = BP_sys, color = race,
                    ymin = lower.sys, ymax = upper.sys)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

## distribution of outcome/outliers for each year of data, by race
ggplot(data = nhanes_data) +
  geom_boxplot(aes(x = svy_year, y = bp_sys_mean,  
                   fill = demo_race)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

## distribution of outcome - for all observations 1999-2006
ggplot(data = data_train1_clean) + geom_histogram(aes(x = bp_sys_mean)) +
  labs(title = "Distribution of Mean Systolic BP",
       x = "BP", y = "Num. observations") +
  geom_vline(xintercept = 130, color = "blue") + #
  geom_vline(xintercept = 140, color = "blue")

```

